// Generated ability constants.
#ifndef GUARD_ABILITIES_IMPORTED_H
#define GUARD_ABILITIES_IMPORTED_H

#define ABILITY_STENCH                   1
#define ABILITY_DRIZZLE                  2
#define ABILITY_SPEED_BOOST              3
#define ABILITY_BATTLE_ARMOR             4
#define ABILITY_STURDY                   5
#define ABILITY_DAMP                     6
#define ABILITY_LIMBER                   7
#define ABILITY_SAND_VEIL                8
#define ABILITY_STATIC                   9
#define ABILITY_VOLT_ABSORB              10
#define ABILITY_WATER_ABSORB             11
#define ABILITY_OBLIVIOUS                12
#define ABILITY_CLOUD_NINE               13
#define ABILITY_COMPOUNDEYES             14
#define ABILITY_INSOMNIA                 15
#define ABILITY_COLOR_CHANGE             16
#define ABILITY_IMMUNITY                 17
#define ABILITY_FLASH_FIRE               18
#define ABILITY_SHIELD_DUST              19
#define ABILITY_OWN_TEMPO                20
#define ABILITY_SUCTION_CUPS             21
#define ABILITY_INTIMIDATE               22
#define ABILITY_SHADOW_TAG               23
#define ABILITY_ROUGH_SKIN               24
#define ABILITY_WONDER_GUARD             25
#define ABILITY_LEVITATE                 26
#define ABILITY_EFFECT_SPORE             27
#define ABILITY_SYNCHRONIZE              28
#define ABILITY_CLEAR_BODY               29
#define ABILITY_NATURAL_CURE             30
#define ABILITY_LIGHTNINGROD             31
#define ABILITY_SERENE_GRACE             32
#define ABILITY_SWIFT_SWIM               33
#define ABILITY_CHLOROPHYLL              34
#define ABILITY_ILLUMINATE               35
#define ABILITY_TRACE                    36
#define ABILITY_HUGE_POWER               37
#define ABILITY_POISON_POINT             38
#define ABILITY_INNER_FOCUS              39
#define ABILITY_MAGMA_ARMOR              40
#define ABILITY_WATER_VEIL               41
#define ABILITY_MAGNET_PULL              42
#define ABILITY_SOUNDPROOF               43
#define ABILITY_RAIN_DISH                44
#define ABILITY_SAND_STREAM              45
#define ABILITY_PRESSURE                 46
#define ABILITY_THICK_FAT                47
#define ABILITY_EARLY_BIRD               48
#define ABILITY_FLAME_BODY               49
#define ABILITY_RUNAWAY                  50
#define ABILITY_KEEN_EYE                 51
#define ABILITY_HYPER_CUTTER             52
#define ABILITY_PICKUP                   53
#define ABILITY_TRUANT                   54
#define ABILITY_HUSTLE                   55
#define ABILITY_CUTE_CHARM               56
#define ABILITY_PLUS                     57
#define ABILITY_MINUS                    58
#define ABILITY_FORECAST                 59
#define ABILITY_STICKY_HOLD              60
#define ABILITY_SHED_SKIN                61
#define ABILITY_GUTS                     62
#define ABILITY_MARVEL_SCALE             63
#define ABILITY_LIQUID_OOZE              64
#define ABILITY_OVERGROW                 65
#define ABILITY_BLAZE                    66
#define ABILITY_TORRENT                  67
#define ABILITY_SWARM                    68
#define ABILITY_ROCK_HEAD                69
#define ABILITY_DROUGHT                  70
#define ABILITY_ARENA_TRAP               71
#define ABILITY_VITAL_SPIRIT             72
#define ABILITY_WHITE_SMOKE              73
#define ABILITY_PURE_POWER               74
#define ABILITY_SHELL_ARMOR              75
#define ABILITY_SNOW_WARNING             76
#define ABILITY_AIR_LOCK                 77
#define ABILITY_UNNAMED                  78
#define ABILITY_UNNAMED_79               79
#define ABILITY_UNNAMED_80               80
#define ABILITY_UNNAMED_81               81
#define ABILITY_SNOW_CLOAK               82
#define ABILITY_GLUTTONY                 83
#define ABILITY_UNNAMED_84               84
#define ABILITY_UNBURDEN                 85
#define ABILITY_UNNAMED_86               86
#define ABILITY_UNNAMED_87               87
#define ABILITY_UNNAMED_88               88
#define ABILITY_UNNAMED_89               89
#define ABILITY_IRON_FIST                90
#define ABILITY_UNNAMED_91               91
#define ABILITY_ADAPTABILITY             92
#define ABILITY_SKILL_LINK               93
#define ABILITY_UNNAMED_94               94
#define ABILITY_UNNAMED_95               95
#define ABILITY_UNNAMED_96               96
#define ABILITY_UNNAMED_97               97
#define ABILITY_SNIPER                   98
#define ABILITY_UNNAMED_99               99
#define ABILITY_NO_GUARD                 100
#define ABILITY_UNNAMED_101              101
#define ABILITY_TECHNICIAN               102
#define ABILITY_UNNAMED_103              103
#define ABILITY_UNNAMED_104              104
#define ABILITY_UNNAMED_105              105
#define ABILITY_SUPER_LUCK               106
#define ABILITY_UNNAMED_107              107
#define ABILITY_UNNAMED_108              108
#define ABILITY_UNNAMED_109              109
#define ABILITY_UNAWARE                  110
#define ABILITY_TINTED_LENS              111
#define ABILITY_FILTER                   112
#define ABILITY_UNNAMED_113              113
#define ABILITY_SCRAPPY                  114
#define ABILITY_UNNAMED_115              115
#define ABILITY_UNNAMED_116              116
#define ABILITY_SOLID_ROCK               117
#define ABILITY_UNNAMED_118              118
#define ABILITY_UNNAMED_119              119
#define ABILITY_UNNAMED_120              120
#define ABILITY_RECKLESS                 121
#define ABILITY_UNNAMED_122              122
#define ABILITY_UNNAMED_123              123
#define ABILITY_UNNAMED_124              124
#define ABILITY_UNNAMED_125              125
#define ABILITY_SHEER_FORCE              126
#define ABILITY_UNNAMED_127              127
#define ABILITY_UNNAMED_128              128
#define ABILITY_DEFIANT                  129
#define ABILITY_DEFEATIST                130
#define ABILITY_UNNAMED_131              131
#define ABILITY_UNNAMED_132              132
#define ABILITY_UNNAMED_133              133
#define ABILITY_UNNAMED_134              134
#define ABILITY_UNNAMED_135              135
#define ABILITY_UNNAMED_136              136
#define ABILITY_MULTISCALE               137
#define ABILITY_TOXIC_BOOST              138
#define ABILITY_FLARE_BOOST              139
#define ABILITY_UNNAMED_140              140
#define ABILITY_UNNAMED_141              141
#define ABILITY_UNNAMED_142              142
#define ABILITY_UNNAMED_143              143
#define ABILITY_UNNAMED_144              144
#define ABILITY_REGENERATOR              145
#define ABILITY_SLUSH_RUSH               146
#define ABILITY_SAND_RUSH                147
#define ABILITY_WONDER_SKIN              148
#define ABILITY_UNNAMED_149              149
#define ABILITY_UNNAMED_150              150
#define ABILITY_UNNAMED_151              151
#define ABILITY_UNNAMED_152              152
#define ABILITY_UNNAMED_153              153
#define ABILITY_MOXIE                    154
#define ABILITY_UNNAMED_155              155
#define ABILITY_UNNAMED_156              156
#define ABILITY_UNNAMED_157              157
#define ABILITY_UNNAMED_158              158
#define ABILITY_UNNAMED_159              159
#define ABILITY_SAND_FORCE               160
#define ABILITY_UNNAMED_161              161
#define ABILITY_UNNAMED_162              162
#define ABILITY_ABYSS_GRACE              163
#define ABILITY_UNNAMED_164              164
#define ABILITY_UNNAMED_165              165
#define ABILITY_UNNAMED_166              166
#define ABILITY_UNNAMED_167              167
#define ABILITY_UNNAMED_168              168
#define ABILITY_PROTEAN                  169
#define ABILITY_FUR_COAT                 170
#define ABILITY_UNNAMED_171              171
#define ABILITY_UNNAMED_172              172
#define ABILITY_COMPETITIVE              173
#define ABILITY_STRONG_JAW               174
#define ABILITY_UNNAMED_175              175
#define ABILITY_UNNAMED_176              176
#define ABILITY_UNNAMED_177              177
#define ABILITY_UNNAMED_178              178
#define ABILITY_MEGA_LAUNCHR             179
#define ABILITY_UNNAMED_180              180
#define ABILITY_UNNAMED_181              181
#define ABILITY_TOUGH_CLAWS              182
#define ABILITY_UNNAMED_183              183
#define ABILITY_UNNAMED_184              184
#define ABILITY_UNNAMED_185              185
#define ABILITY_UNNAMED_186              186
#define ABILITY_UNNAMED_187              187
#define ABILITY_UNNAMED_188              188
#define ABILITY_UNNAMED_189              189
#define ABILITY_UNNAMED_190              190
#define ABILITY_UNNAMED_191              191
#define ABILITY_UNNAMED_192              192
#define ABILITY_UNNAMED_193              193
#define ABILITY_UNNAMED_194              194
#define ABILITY_UNNAMED_195              195
#define ABILITY_UNNAMED_196              196
#define ABILITY_UNNAMED_197              197
#define ABILITY_UNNAMED_198              198
#define ABILITY_UNNAMED_199              199
#define ABILITY_UNNAMED_200              200
#define ABILITY_UNNAMED_201              201
#define ABILITY_UNNAMED_202              202
#define ABILITY_UNNAMED_203              203
#define ABILITY_UNNAMED_204              204
#define ABILITY_UNNAMED_205              205
#define ABILITY_UNNAMED_206              206
#define ABILITY_UNNAMED_207              207
#define ABILITY_UNNAMED_208              208
#define ABILITY_UNNAMED_209              209
#define ABILITY_UNNAMED_210              210
#define ABILITY_UNNAMED_211              211
#define ABILITY_UNNAMED_212              212
#define ABILITY_UNNAMED_213              213
#define ABILITY_UNNAMED_214              214
#define ABILITY_UNNAMED_215              215
#define ABILITY_UNNAMED_216              216
#define ABILITY_UNNAMED_217              217
#define ABILITY_UNNAMED_218              218
#define ABILITY_UNNAMED_219              219
#define ABILITY_UNNAMED_220              220
#define ABILITY_UNNAMED_221              221
#define ABILITY_UNNAMED_222              222
#define ABILITY_UNNAMED_223              223
#define ABILITY_UNNAMED_224              224
#define ABILITY_UNNAMED_225              225
#define ABILITY_UNNAMED_226              226
#define ABILITY_UNNAMED_227              227
#define ABILITY_UNNAMED_228              228
#define ABILITY_UNNAMED_229              229
#define ABILITY_UNNAMED_230              230
#define ABILITY_UNNAMED_231              231
#define ABILITY_UNNAMED_232              232
#define ABILITY_UNNAMED_233              233
#define ABILITY_ABYSS_BOOST              234
#define ABILITY_RADIANCE                 235
#define ABILITY_BOTANIST                 236
#define ABILITY_EERIE_AURA               237
#define ABILITY_VENOM_BLOOD              238
#define ABILITY_ARCANIST                 239
#define ABILITY_JUNGLE_KING              240
#define ABILITY_OMNIHUNTER               241
#define ABILITY_FAFNIR                   242
#define ABILITY_SINGULARITY              243
#define ABILITY_UNNAMED_244              244
#define ABILITY_UNNAMED_245              245
#define ABILITY_PRISM_LENS               246
#define ABILITY_GALE_WINGS               247
#define ABILITY_DRAGON_FRUIT             248
#define ABILITY_OMNI_CHASE               249
#define ABILITY_PRANKSTER                250
#define ABILITY_SOVEREIGNTY              251
#define ABILITY_INTENSE_CARE             252
#define ABILITY_UNNAMED_253              253
#define ABILITY_UNNAMED_254              254
#define ABILITY_UNNAMED_255              255

#endif
