// Generated move constants (FireRed internal index -> MOVE_*).
#ifndef GUARD_MOVES_IMPORTED_H
#define GUARD_MOVES_IMPORTED_H

#define MOVE_UNNAMED                     0
#define MOVE_POUND                       1
#define MOVE_KARATE_CHOP                 2
#define MOVE_DOUBLESLAP                  3
#define MOVE_BULLET_PUNCH                4
#define MOVE_MEGA_PUNCH                  5
#define MOVE_PAY_DAY                     6
#define MOVE_FIRE_PUNCH                  7
#define MOVE_ICE_PUNCH                   8
#define MOVE_THUNDERPUNCH                9
#define MOVE_SCRATCH                     10
#define MOVE_VICEGRIP                    11
#define MOVE_FLARE_BLITZ                 12
#define MOVE_SHADOW_CLAW                 13
#define MOVE_SWORDS_DANCE                14
#define MOVE_MEMENTO                     15
#define MOVE_GUST                        16
#define MOVE_WING_ATTACK                 17
#define MOVE_HURRICANE                   18
#define MOVE_FLY                         19
#define MOVE_BIND                        20
#define MOVE_SLAM                        21
#define MOVE_VINE_WHIP                   22
#define MOVE_STOMP                       23
#define MOVE_DOUBLE_KICK                 24
#define MOVE_MEGA_KICK                   25
#define MOVE_JUMP_KICK                   26
#define MOVE_ROLLING_KICK                27
#define MOVE_SAND_ATTACK                 28
#define MOVE_HEADBUTT                    29
#define MOVE_HORN_ATTACK                 30
#define MOVE_FURY_ATTACK                 31
#define MOVE_DRILL_RUN                   32
#define MOVE_TACKLE                      33
#define MOVE_BODY_SLAM                   34
#define MOVE_WRAP                        35
#define MOVE_TAKE_DOWN                   36
#define MOVE_THRASH                      37
#define MOVE_DOUBLE_EDGE                 38
#define MOVE_TAIL_WHIP                   39
#define MOVE_POISON_STING                40
#define MOVE_QUIVER_DANCE                41
#define MOVE_PIN_MISSILE                 42
#define MOVE_LEER                        43
#define MOVE_BITE                        44
#define MOVE_GROWL                       45
#define MOVE_SNARL                       46
#define MOVE_SING                        47
#define MOVE_SUPERSONIC                  48
#define MOVE_SONICBOOM                   49
#define MOVE_DISABLE                     50
#define MOVE_ACID                        51
#define MOVE_EMBER                       52
#define MOVE_FLAMETHROWER                53
#define MOVE_MIST                        54
#define MOVE_WATER_GUN                   55
#define MOVE_HYDRO_PUMP                  56
#define MOVE_SURF                        57
#define MOVE_ICE_BEAM                    58
#define MOVE_BLIZZARD                    59
#define MOVE_PSYBEAM                     60
#define MOVE_BUBBLEBEAM                  61
#define MOVE_AURORA_BEAM                 62
#define MOVE_HYPER_BEAM                  63
#define MOVE_PECK                        64
#define MOVE_DRILL_PECK                  65
#define MOVE_SUBMISSION                  66
#define MOVE_LOW_KICK                    67
#define MOVE_COUNTER                     68
#define MOVE_SEISMIC_TOSS                69
#define MOVE_RAGE_FIST                   70
#define MOVE_ABSORB                      71
#define MOVE_MEGA_DRAIN                  72
#define MOVE_LEECH_SEED                  73
#define MOVE_GROWTH                      74
#define MOVE_RAZOR_LEAF                  75
#define MOVE_SOLAR_BEAM                  76
#define MOVE_POISONPOWDER                77
#define MOVE_STUN_SPORE                  78
#define MOVE_SLEEP_POWDER                79
#define MOVE_PETAL_DANCE                 80
#define MOVE_STRING_SHOT                 81
#define MOVE_DRAGON_RUSH                 82
#define MOVE_FIRE_SPIN                   83
#define MOVE_THUNDERSHOCK                84
#define MOVE_THUNDERBOLT                 85
#define MOVE_THUNDER_WAVE                86
#define MOVE_THUNDER                     87
#define MOVE_ROCK_THROW                  88
#define MOVE_EARTHQUAKE                  89
#define MOVE_EARTH_POWER                 90
#define MOVE_DIG                         91
#define MOVE_TOXIC                       92
#define MOVE_CONFUSION                   93
#define MOVE_PSYCHIC                     94
#define MOVE_HYPNOSIS                    95
#define MOVE_MEDITATE                    96
#define MOVE_AGILITY                     97
#define MOVE_QUICK_ATTACK                98
#define MOVE_RAGE                        99
#define MOVE_TELEPORT                    100
#define MOVE_NIGHT_SHADE                 101
#define MOVE_MIMIC                       102
#define MOVE_SCREECH                     103
#define MOVE_DOUBLE_TEAM                 104
#define MOVE_RECOVER                     105
#define MOVE_HARDEN                      106
#define MOVE_MINIMIZE                    107
#define MOVE_SMOKESCREEN                 108
#define MOVE_CONFUSE_RAY                 109
#define MOVE_WITHDRAW                    110
#define MOVE_DEFENSE_CURL                111
#define MOVE_BARRIER                     112
#define MOVE_LIGHT_SCREEN                113
#define MOVE_HAZE                        114
#define MOVE_REFLECT                     115
#define MOVE_FOCUS_ENERGY                116
#define MOVE_BIDE                        117
#define MOVE_METRONOME                   118
#define MOVE_MIRROR_MOVE                 119
#define MOVE_SELFDESTRUCT                120
#define MOVE_EGG_BOMB                    121
#define MOVE_LICK                        122
#define MOVE_SMOG                        123
#define MOVE_SLUDGE                      124
#define MOVE_BONE_CLUB                   125
#define MOVE_FIRE_BLAST                  126
#define MOVE_WATERFALL                   127
#define MOVE_CLAMP                       128
#define MOVE_SWIFT                       129
#define MOVE_ZEN_HEADBUTT                130
#define MOVE_ELECTROSHOCK                131
#define MOVE_CONSTRICT                   132
#define MOVE_AMNESIA                     133
#define MOVE_AURA_SPHERE                 134
#define MOVE_SOFTBOILED                  135
#define MOVE_HI_JUMP_KICK                136
#define MOVE_GLARE                       137
#define MOVE_DREAM_EATER                 138
#define MOVE_POISON_GAS                  139
#define MOVE_BUG_BUZZ                    140
#define MOVE_LEECH_LIFE                  141
#define MOVE_LOVELY_KISS                 142
#define MOVE_BRAVE_BIRD                  143
#define MOVE_ABYSS_MIASMA                144
#define MOVE_AQUA_JET                    145
#define MOVE_DIZZY_PUNCH                 146
#define MOVE_SPORE                       147
#define MOVE_MET_ASSAULT                 148
#define MOVE_DARK_PULSE                  149
#define MOVE_SPLASH                      150
#define MOVE_ACID_ARMOR                  151
#define MOVE_CRABHAMMER                  152
#define MOVE_EXPLOSION                   153
#define MOVE_FURY_SWIPES                 154
#define MOVE_BONEMERANG                  155
#define MOVE_REST                        156
#define MOVE_ROCK_SLIDE                  157
#define MOVE_HYPER_FANG                  158
#define MOVE_FLASH_CANNON                159
#define MOVE_HEAL                        160
#define MOVE_TRI_ATTACK                  161
#define MOVE_SUPER_FANG                  162
#define MOVE_SLASH                       163
#define MOVE_SUBSTITUTE                  164
#define MOVE_STRUGGLE                    165
#define MOVE_ABYSS_WRATH                 166
#define MOVE_TRIPLE_KICK                 167
#define MOVE_THIEF                       168
#define MOVE_ELECTROWEB                  169
#define MOVE_MIND_READER                 170
#define MOVE_NIGHTMARE                   171
#define MOVE_FLAME_WHEEL                 172
#define MOVE_SNORE                       173
#define MOVE_CURSE                       174
#define MOVE_FLAIL                       175
#define MOVE_CONVERSION_2                176
#define MOVE_AEROBLAST                   177
#define MOVE_COTTONSPORE                 178
#define MOVE_REVERSAL                    179
#define MOVE_HEX                         180
#define MOVE_POWDER_SNOW                 181
#define MOVE_PROTECT                     182
#define MOVE_MACH_PUNCH                  183
#define MOVE_SCARY_FACE                  184
#define MOVE_FEINT_ATTACK                185
#define MOVE_SWEET_KISS                  186
#define MOVE_BELLY_DRUM                  187
#define MOVE_SLUDGE_BOMB                 188
#define MOVE_MUD_SLAP                    189
#define MOVE_OCTAZOOKA                   190
#define MOVE_SPIKES                      191
#define MOVE_ZAP_CANNON                  192
#define MOVE_ICE_SHARD                   193
#define MOVE_SHADOW_SNEAK                194
#define MOVE_DRAGON_PULSE                195
#define MOVE_ICY_WIND                    196
#define MOVE_DETECT                      197
#define MOVE_BONE_RUSH                   198
#define MOVE_LOCK_ON                     199
#define MOVE_OUTRAGE                     200
#define MOVE_SANDSTORM                   201
#define MOVE_GIGA_DRAIN                  202
#define MOVE_ENDURE                      203
#define MOVE_CHARM                       204
#define MOVE_ROLLOUT                     205
#define MOVE_FALSE_SWIPE                 206
#define MOVE_SWAGGER                     207
#define MOVE_MILK_DRINK                  208
#define MOVE_SPARK                       209
#define MOVE_FURY_CUTTER                 210
#define MOVE_STEEL_WING                  211
#define MOVE_DRAIN_PUNCH                 212
#define MOVE_ATTRACT                     213
#define MOVE_SLEEP_TALK                  214
#define MOVE_HEAL_BELL                   215
#define MOVE_RETURN                      216
#define MOVE_BULLDOZE                    217
#define MOVE_FRUSTRATION                 218
#define MOVE_SAFEGUARD                   219
#define MOVE_PAIN_SPLIT                  220
#define MOVE_SACRED_FIRE                 221
#define MOVE_MAGNITUDE                   222
#define MOVE_DYNAMICPUNCH                223
#define MOVE_MEGAHORN                    224
#define MOVE_DRAGONBREATH                225
#define MOVE_BATON_PASS                  226
#define MOVE_ENCORE                      227
#define MOVE_PURSUIT                     228
#define MOVE_RAPID_SPIN                  229
#define MOVE_SWEET_SCENT                 230
#define MOVE_IRON_TAIL                   231
#define MOVE_METAL_CLAW                  232
#define MOVE_VITAL_THROW                 233
#define MOVE_MORNING_SUN                 234
#define MOVE_SYNTHESIS                   235
#define MOVE_MOONLIGHT                   236
#define MOVE_WATER_TACKLE                237
#define MOVE_CROSS_CHOP                  238
#define MOVE_TWISTER                     239
#define MOVE_RAIN_DANCE                  240
#define MOVE_SUNNY_DAY                   241
#define MOVE_CRUNCH                      242
#define MOVE_MIRROR_COAT                 243
#define MOVE_PSYCH_UP                    244
#define MOVE_EXTREMESPEED                245
#define MOVE_ANCIENTPOWER                246
#define MOVE_SHADOW_BALL                 247
#define MOVE_LEAF_STORM                  248
#define MOVE_ROCK_SMASH                  249
#define MOVE_WHIRLPOOL                   250
#define MOVE_BEAT_UP                     251
#define MOVE_FAKE_OUT                    252
#define MOVE_UPROAR                      253
#define MOVE_STOCKPILE                   254
#define MOVE_SPIT_UP                     255
#define MOVE_SWALLOW                     256
#define MOVE_HEAT_WAVE                   257
#define MOVE_HAIL                        258
#define MOVE_TORMENT                     259
#define MOVE_FLATTER                     260
#define MOVE_WILL_O_WISP                 261
#define MOVE_SCALD                       262
#define MOVE_FACADE                      263
#define MOVE_FOCUS_PUNCH                 264
#define MOVE_IRON_HEAD                   265
#define MOVE_FOLLOW_ME                   266
#define MOVE_NATURE_POWER                267
#define MOVE_CHARGE                      268
#define MOVE_TAUNT                       269
#define MOVE_HELPING_HAND                270
#define MOVE_TRICK                       271
#define MOVE_MAGNET_BOMB                 272
#define MOVE_WISH                        273
#define MOVE_MUD_BOMB                    274
#define MOVE_INGRAIN                     275
#define MOVE_SUPERPOWER                  276
#define MOVE_X_SCISSOR                   277
#define MOVE_NIGHT_SLASH                 278
#define MOVE_REVENGE                     279
#define MOVE_BRICK_BREAK                 280
#define MOVE_YAWN                        281
#define MOVE_KNOCK_OFF                   282
#define MOVE_ENDEAVOR                    283
#define MOVE_ERUPTION                    284
#define MOVE_SKILL_SWAP                  285
#define MOVE_POWER_GEM                   286
#define MOVE_REFRESH                     287
#define MOVE_MYSTICALFIRE                288
#define MOVE_SNATCH                      289
#define MOVE_POISON_JAB                  290
#define MOVE_PHANTOMFORCE                291
#define MOVE_ARM_THRUST                  292
#define MOVE_SEED_BOMB                   293
#define MOVE_TAIL_GLOW                   294
#define MOVE_STONE_EDGE                  295
#define MOVE_SHELL_SMASH                 296
#define MOVE_ROOST                       297
#define MOVE_TEETER_DANCE                298
#define MOVE_BLAZE_KICK                  299
#define MOVE_RAGE_POWDER                 300
#define MOVE_STONE_AXE                   301
#define MOVE_NEEDLE_ARM                  302
#define MOVE_SLACK_OFF                   303
#define MOVE_HYPER_VOICE                 304
#define MOVE_POISON_FANG                 305
#define MOVE_CRUSH_CLAW                  306
#define MOVE_BOOMBURST                   307
#define MOVE_INFESTATION                 308
#define MOVE_METEOR_MASH                 309
#define MOVE_ASTONISH                    310
#define MOVE_WEATHER_BALL                311
#define MOVE_AROMATHERAPY                312
#define MOVE_FAKE_TEARS                  313
#define MOVE_AIR_CUTTER                  314
#define MOVE_OVERHEAT                    315
#define MOVE_POWERUPPUNCH                316
#define MOVE_ROCK_TOMB                   317
#define MOVE_SILVER_WIND                 318
#define MOVE_METAL_SOUND                 319
#define MOVE_HEAD_SMASH                  320
#define MOVE_TICKLE                      321
#define MOVE_COSMIC_POWER                322
#define MOVE_WATER_SPOUT                 323
#define MOVE_SIGNAL_BEAM                 324
#define MOVE_SHADOW_PUNCH                325
#define MOVE_EXTRASENSORY                326
#define MOVE_SKY_UPPERCUT                327
#define MOVE_SAND_TOMB                   328
#define MOVE_HIHORSEPOWER                329
#define MOVE_MUDDY_WATER                 330
#define MOVE_BULLET_SEED                 331
#define MOVE_AERIAL_ACE                  332
#define MOVE_ICICLE_SPEAR                333
#define MOVE_IRON_DEFENSE                334
#define MOVE_ROCK_POLISH                 335
#define MOVE_HOWL                        336
#define MOVE_DRAGON_CLAW                 337
#define MOVE_ICICLE_CRASH                338
#define MOVE_BULK_UP                     339
#define MOVE_YGGDRAIN                    340
#define MOVE_MUD_SHOT                    341
#define MOVE_POISON_TAIL                 342
#define MOVE_COVET                       343
#define MOVE_WILD_CHARGE                 344
#define MOVE_MAGICAL_LEAF                345
#define MOVE_COTTON_GUARD                346
#define MOVE_CALM_MIND                   347
#define MOVE_LEAF_BLADE                  348
#define MOVE_DRAGON_DANCE                349
#define MOVE_ROCK_BLAST                  350
#define MOVE_SHOCK_WAVE                  351
#define MOVE_WATER_PULSE                 352
#define MOVE_DOOM_DESIRE                 353
#define MOVE_NASTY_PLOT                  354
#define MOVE_LIGHT_SHOT                  355
#define MOVE_ASTRAL_GLEAM                356
#define MOVE_RADIANT_STAR                357
#define MOVE_METEOR                      358
#define MOVE_ETHERIC_BOON                359
#define MOVE_AD_NIHILO                   360
#define MOVE_FINAL_GAMBIT                361
#define MOVE_MIND_BASH                   362
#define MOVE_COSMIC_SLASH                363
#define MOVE_ENERGY_EDGE                 364
#define MOVE__5_RING_SWORD               365
#define MOVE_SHOGUN_DECOY                366
#define MOVE_CHIME_BOOST                 367
#define MOVE_SOUL_TRADE                  368
#define MOVE_MEGALODIVE                  369
#define MOVE_AZURE_FLOOD                 370
#define MOVE_SUCKER_PUNCH                371
#define MOVE_SEALINGLIGHT                372
#define MOVE_CLOSE_COMBAT                373
#define MOVE_AIR_SLASH                   374
#define MOVE_TRIPLE_AXEL                 375
#define MOVE_FIRE_FANG                   376
#define MOVE_ICE_FANG                    377
#define MOVE_THUNDER_FANG                378
#define MOVE_TAIL_SLAP                   379
#define MOVE_HORN_LEECH                  380
#define MOVE_LIFE_CONTROL                381
#define MOVE_STAR_DROP                   382
#define MOVE_TRAILBLAZE                  383
#define MOVE_FLAME_CHARGE                384
#define MOVE_SOLAR_BLADE                 385
#define MOVE_FIRST_PRESS                 386
#define MOVE_VOLT_SWITCH                 387
#define MOVE_U_TURN                      388
#define MOVE_SUMMER_TANGO                389
#define MOVE_SPRING_TANGO                390
#define MOVE_BRIGHT_SONG                 391
#define MOVE_LIFE_BALLAD                 392
#define MOVE_RAPID_FIRE                  393
#define MOVE_TOXIC_REAP                  394
#define MOVE_WILT_MIASMA                 395
#define MOVE_LADYBUG_RUSH                396
#define MOVE_COIL                        397
#define MOVE_FOUL_PLAY                   398
#define MOVE_VOLT_WINGS                  399
#define MOVE_FLIP_TURN                   400
#define MOVE_CRAZED_SHOUT                401
#define MOVE_WHIP_RIPPER                 402
#define MOVE_PHALANXGUARD                403
#define MOVE_DOUBLEHAMMER                404
#define MOVE_STOMP_CRUSH                 405
#define MOVE_ICY_ARIA                    406
#define MOVE_VENOM_GUST                  407
#define MOVE_YGGDRASLASH                 408
#define MOVE_WATER_BOMB                  409
#define MOVE_SUBZERO_GALE                410
#define MOVE_FROST_CURSE                 411
#define MOVE_DIVINE_STORM                412
#define MOVE_IZUNA                       413
#define MOVE_FUKUBARI                    414
#define MOVE_KUMOGAKURE                  415
#define MOVE_TAGEN_BATTOU                416
#define MOVE_NOBLE_ORDER                 417
#define MOVE_VEIL_ORDER                  418
#define MOVE_SPOREBARRAGE                419
#define MOVE_CHAINWEATHER                420
#define MOVE_CHAIN_KILLER                421
#define MOVE_CORKSCREW                   422
#define MOVE_TITAN_KILLER                423
#define MOVE_ONE_TWOPUNCH                424
#define MOVE_LEADING_BLOW                425
#define MOVE_DARKNESSFIST                426
#define MOVE_WAKINGCHAKRA                427
#define MOVE_CALL_SNAKE                  428
#define MOVE_CALL_OWL                    429
#define MOVE_CALL_LION                   430
#define MOVE_CALL_ALLIES                 431
#define MOVE_PRIMAL_DRUMS                432
#define MOVE_MESMERIZE                   433
#define MOVE_ROTTEN_EGG                  434
#define MOVE_HARVESTPARTY                435
#define MOVE_LULLABY                     436
#define MOVE_STRANGESEEDS                437
#define MOVE_PANIC_SPORES                438
#define MOVE_ATROPHIC_EYE                439
#define MOVE_WARDING_MIST                440
#define MOVE_TIME_CIRCLE                 441
#define MOVE_ARCANE_BLAST                442
#define MOVE_WOBBUSHIELD                 443
#define MOVE_SCYTHE_DANCE                444
#define MOVE_DUALWINGBEAT                445
#define MOVE_SONIC_RAID                  446
#define MOVE_AKASHIC_NOVA                447
#define MOVE_LIMIT_BREAK                 448
#define MOVE_SLASHRAMPAGE                449
#define MOVE_FREEZERIPPLE                450
#define MOVE_OCEAN_RAVE                  451
#define MOVE_ROYAL_ORDER                 452
#define MOVE_VOLT_MASK                   453
#define MOVE_FLARE_MASK                  454
#define MOVE_FREEZE_MASK                 455
#define MOVE_ACCELEROCK                  456
#define MOVE_IRON_DRILL                  457
#define MOVE_SHIFT_GEAR                  458
#define MOVE_GUNK_SHOT                   459
#define MOVE_CELL_SHIELD                 460
#define MOVE_DEMONIC_RUSH                461
#define MOVE_SOLAR_FLAME                 462
#define MOVE_DEMON_RAGE                  463
#define MOVE_RISING_CLAW                 464
#define MOVE_HYDRO_STEAM                 465
#define MOVE_THUNDERCLAP                 466
#define MOVE_FIERYBULWARK                467
#define MOVE_ABYSS_BLAZE                 468
#define MOVE_ORIGIN_CRUSH                469
#define MOVE_BAFFLINGSTEP                470
#define MOVE_TOXIC_HERB                  471
#define MOVE_WEIRD_POTION                472
#define MOVE_POTION_BOMB                 473
#define MOVE_WING_TALON                  474
#define MOVE_ROCK_HAMMER                 475
#define MOVE_SHATTER_SHOT                476
#define MOVE_TWINEEDLE                   477
#define MOVE_MOVE_478                    478
#define MOVE_MOVE_479                    479
#define MOVE_MOVE_480                    480
#define MOVE_MOVE_481                    481
#define MOVE_MOVE_482                    482

#endif
