// Generated species constants (FireRed internal index -> SPECIES_*).
// Reconcile with your project's existing species enum before use.
#ifndef GUARD_SPECIES_IMPORTED_H
#define GUARD_SPECIES_IMPORTED_H

#define SPECIES_UNNAMED                  0   // natDex 0
#define SPECIES_BULBASAUR                1   // natDex 1
#define SPECIES_IVYSAUR                  2   // natDex 2
#define SPECIES_VENUSAUR                 3   // natDex 3
#define SPECIES_CHARMANDER               4   // natDex 4
#define SPECIES_CHARMELEON               5   // natDex 5
#define SPECIES_CHARIZARD                6   // natDex 6
#define SPECIES_SQUIRTLE                 7   // natDex 7
#define SPECIES_WARTORTLE                8   // natDex 8
#define SPECIES_BLASTOISE                9   // natDex 9
#define SPECIES_CATERPIE                 10   // natDex 10
#define SPECIES_METAPOD                  11   // natDex 11
#define SPECIES_BUTTERFREE               12   // natDex 12
#define SPECIES_WEEDLE                   13   // natDex 13
#define SPECIES_KAKUNA                   14   // natDex 14
#define SPECIES_BEEDRILL                 15   // natDex 15
#define SPECIES_PIDGEY                   16   // natDex 16
#define SPECIES_PIDGEOTTO                17   // natDex 17
#define SPECIES_PIDGEOT                  18   // natDex 18
#define SPECIES_RATTATA                  19   // natDex 19
#define SPECIES_RATREECATE               20   // natDex 20
#define SPECIES_SPEAROW                  21   // natDex 21
#define SPECIES_FEAROW                   22   // natDex 22
#define SPECIES_EKANS                    23   // natDex 23
#define SPECIES_ARBOK                    24   // natDex 24
#define SPECIES_PIKACHU                  25   // natDex 25
#define SPECIES_RAICHU                   26   // natDex 26
#define SPECIES_SANDSHREW                27   // natDex 27
#define SPECIES_SANDSLASH                28   // natDex 28
#define SPECIES_NIDORAN_SF               29   // natDex 29
#define SPECIES_NIDORINA                 30   // natDex 30
#define SPECIES_NIDOQUEEN                31   // natDex 31
#define SPECIES_NIDORAN_SM               32   // natDex 32
#define SPECIES_NIDORINO                 33   // natDex 33
#define SPECIES_NIDOKING                 34   // natDex 34
#define SPECIES_CLEFAIRY                 35   // natDex 35
#define SPECIES_CLEFABLE                 36   // natDex 36
#define SPECIES_VULPIX                   37   // natDex 37
#define SPECIES_NINETALES                38   // natDex 38
#define SPECIES_JIGGLYPUFF               39   // natDex 39
#define SPECIES_WIGGLYTUFF               40   // natDex 40
#define SPECIES_ZUBAT                    41   // natDex 41
#define SPECIES_GOLBAT                   42   // natDex 42
#define SPECIES_ODDISH                   43   // natDex 43
#define SPECIES_GLOOM                    44   // natDex 44
#define SPECIES_VILEPLUME                45   // natDex 45
#define SPECIES_PARAS                    46   // natDex 46
#define SPECIES_PARASECT                 47   // natDex 47
#define SPECIES_VENONAT                  48   // natDex 48
#define SPECIES_VENOMOTH                 49   // natDex 49
#define SPECIES_DIGLETT                  50   // natDex 50
#define SPECIES_DUGTRIO                  51   // natDex 51
#define SPECIES_MEOWTH                   52   // natDex 52
#define SPECIES_PERSIAN                  53   // natDex 53
#define SPECIES_PSYDUCK                  54   // natDex 54
#define SPECIES_GOLDUCK                  55   // natDex 55
#define SPECIES_MANKEY                   56   // natDex 56
#define SPECIES_PRIMEAPE                 57   // natDex 57
#define SPECIES_GROWLITHE                58   // natDex 58
#define SPECIES_ARCANINE                 59   // natDex 59
#define SPECIES_POLIWAG                  60   // natDex 60
#define SPECIES_POLIWHIRL                61   // natDex 61
#define SPECIES_POLIWRATH                62   // natDex 62
#define SPECIES_ABRA                     63   // natDex 63
#define SPECIES_KADABRA                  64   // natDex 64
#define SPECIES_ALAKAZAM                 65   // natDex 65
#define SPECIES_MACHOP                   66   // natDex 66
#define SPECIES_MACHOKE                  67   // natDex 67
#define SPECIES_MACHAMP                  68   // natDex 68
#define SPECIES_BELLSPROUT               69   // natDex 69
#define SPECIES_WEEPINBELL               70   // natDex 70
#define SPECIES_VICTREEBEL               71   // natDex 71
#define SPECIES_TENTACOOL                72   // natDex 72
#define SPECIES_TENTACRUEL               73   // natDex 73
#define SPECIES_GEODUDE                  74   // natDex 74
#define SPECIES_GRAVELER                 75   // natDex 75
#define SPECIES_GOLEM                    76   // natDex 76
#define SPECIES_PONYTA                   77   // natDex 77
#define SPECIES_RAPIDASH                 78   // natDex 78
#define SPECIES_SLOWPOKE                 79   // natDex 79
#define SPECIES_SLOWBRO                  80   // natDex 80
#define SPECIES_MAGNEMITE                81   // natDex 81
#define SPECIES_MAGNETON                 82   // natDex 82
#define SPECIES_FARFETCH_D               83   // natDex 83
#define SPECIES_DODUO                    84   // natDex 84
#define SPECIES_DODRIO                   85   // natDex 85
#define SPECIES_SEEL                     86   // natDex 86
#define SPECIES_DEWGONG                  87   // natDex 87
#define SPECIES_GRIMER                   88   // natDex 88
#define SPECIES_MUK                      89   // natDex 89
#define SPECIES_SHELLDER                 90   // natDex 90
#define SPECIES_CLOYSTER                 91   // natDex 91
#define SPECIES_GASTLY                   92   // natDex 92
#define SPECIES_HAUNTER                  93   // natDex 93
#define SPECIES_GENGAR                   94   // natDex 94
#define SPECIES_ONIX                     95   // natDex 95
#define SPECIES_DROWZEE                  96   // natDex 96
#define SPECIES_HYPNO                    97   // natDex 97
#define SPECIES_KRABBY                   98   // natDex 98
#define SPECIES_KINGLER                  99   // natDex 99
#define SPECIES_VOLTORB                  100   // natDex 100
#define SPECIES_ELECTRODE                101   // natDex 101
#define SPECIES_EXEGGCUTE                102   // natDex 102
#define SPECIES_EXEGGUTOR                103   // natDex 103
#define SPECIES_CUBONE                   104   // natDex 104
#define SPECIES_MAROWAK                  105   // natDex 105
#define SPECIES_HITMONLEE                106   // natDex 106
#define SPECIES_HITMONCHAN               107   // natDex 107
#define SPECIES_LICKITUNG                108   // natDex 108
#define SPECIES_KOFFING                  109   // natDex 109
#define SPECIES_WEEZING                  110   // natDex 110
#define SPECIES_RHYHORN                  111   // natDex 111
#define SPECIES_RHYDON                   112   // natDex 112
#define SPECIES_CHANSEY                  113   // natDex 113
#define SPECIES_TANGELA                  114   // natDex 114
#define SPECIES_KANGASKHAN               115   // natDex 115
#define SPECIES_HORSEA                   116   // natDex 116
#define SPECIES_SEADRA                   117   // natDex 117
#define SPECIES_GOLDEEN                  118   // natDex 118
#define SPECIES_SEAKING                  119   // natDex 119
#define SPECIES_STARYU                   120   // natDex 120
#define SPECIES_STARMIE                  121   // natDex 121
#define SPECIES_MR_MIME                  122   // natDex 122
#define SPECIES_SCYTHER                  123   // natDex 123
#define SPECIES_JYNX                     124   // natDex 124
#define SPECIES_ELECTABUZZ               125   // natDex 125
#define SPECIES_MAGMAR                   126   // natDex 126
#define SPECIES_PINSIR                   127   // natDex 127
#define SPECIES_TAUROS                   128   // natDex 128
#define SPECIES_MAGIKARP                 129   // natDex 129
#define SPECIES_GYARADOS                 130   // natDex 130
#define SPECIES_LAPRAS                   131   // natDex 131
#define SPECIES_KLEAVOR                  132   // natDex 132
#define SPECIES_EEVEE                    133   // natDex 133
#define SPECIES_VAPOREON                 134   // natDex 134
#define SPECIES_JOLTEON                  135   // natDex 135
#define SPECIES_FLAREON                  136   // natDex 136
#define SPECIES_PORYGON                  137   // natDex 137
#define SPECIES_OMANYTE                  138   // natDex 138
#define SPECIES_OMASTAR                  139   // natDex 139
#define SPECIES_KABUTO                   140   // natDex 140
#define SPECIES_KABUTOPS                 141   // natDex 141
#define SPECIES_AERODACTYL               142   // natDex 142
#define SPECIES_SNORLAX                  143   // natDex 143
#define SPECIES_FARFETCH_D_144           144   // natDex 144
#define SPECIES_SIRFETCH_D               145   // natDex 145
#define SPECIES_STANTLER                 146   // natDex 146
#define SPECIES_DRATINI                  147   // natDex 147
#define SPECIES_DRAGONAIR                148   // natDex 148
#define SPECIES_DRAGONITE                149   // natDex 149
#define SPECIES_KECLEON                  150   // natDex 150
#define SPECIES_MAWILE                   151   // natDex 151
#define SPECIES_CHIKORITA                152   // natDex 152
#define SPECIES_BAYLEEF                  153   // natDex 153
#define SPECIES_MEGANIUM                 154   // natDex 154
#define SPECIES_CYNDAQUIL                155   // natDex 155
#define SPECIES_QUILAVA                  156   // natDex 156
#define SPECIES_TYPHLOSION               157   // natDex 157
#define SPECIES_TOTODILE                 158   // natDex 158
#define SPECIES_CROCONAW                 159   // natDex 159
#define SPECIES_FERALIGATR               160   // natDex 160
#define SPECIES_SENTRET                  161   // natDex 161
#define SPECIES_FURRET                   162   // natDex 162
#define SPECIES_HOOTHOOT                 163   // natDex 163
#define SPECIES_NOCTOWL                  164   // natDex 164
#define SPECIES_LEDYBA                   165   // natDex 165
#define SPECIES_LEDIAN                   166   // natDex 166
#define SPECIES_SPINARAK                 167   // natDex 167
#define SPECIES_ARIADOS                  168   // natDex 168
#define SPECIES_CROBAT                   169   // natDex 169
#define SPECIES_CHINCHOU                 170   // natDex 170
#define SPECIES_LANTURN                  171   // natDex 171
#define SPECIES_SCREAMTAIL               172   // natDex 172
#define SPECIES_SANDYSHOCK               173   // natDex 173
#define SPECIES_FLUT_MANE                174   // natDex 174
#define SPECIES_TOGEPI                   175   // natDex 175
#define SPECIES_TOGETIC                  176   // natDex 176
#define SPECIES_NATU                     177   // natDex 177
#define SPECIES_XATU                     178   // natDex 178
#define SPECIES_MAREEP                   179   // natDex 179
#define SPECIES_FLAAFFY                  180   // natDex 180
#define SPECIES_AMPHAROS                 181   // natDex 181
#define SPECIES_BELLOSSOM                182   // natDex 182
#define SPECIES_MARILL                   183   // natDex 183
#define SPECIES_AZUMARILL                184   // natDex 184
#define SPECIES_SUDOWOODO                185   // natDex 185
#define SPECIES_POLITOED                 186   // natDex 186
#define SPECIES_HOPPIP                   187   // natDex 187
#define SPECIES_SKIPLOOM                 188   // natDex 188
#define SPECIES_JUMPLUFF                 189   // natDex 189
#define SPECIES_AIPOM                    190   // natDex 190
#define SPECIES_SUNKERN                  191   // natDex 191
#define SPECIES_SUNFLORA                 192   // natDex 192
#define SPECIES_YANMA                    193   // natDex 193
#define SPECIES_WOOPER                   194   // natDex 194
#define SPECIES_QUAGSIRE                 195   // natDex 195
#define SPECIES_ESPEON                   196   // natDex 196
#define SPECIES_UMBREON                  197   // natDex 197
#define SPECIES_MURKROW                  198   // natDex 198
#define SPECIES_SLOWKING                 199   // natDex 199
#define SPECIES_MISDREAVUS               200   // natDex 200
#define SPECIES_GOROCHU                  201   // natDex 201
#define SPECIES_WOBBUFFET                202   // natDex 202
#define SPECIES_GIRAFARIG                203   // natDex 203
#define SPECIES_PINECO                   204   // natDex 204
#define SPECIES_FORRETRESS               205   // natDex 205
#define SPECIES_DUNSPARCE                206   // natDex 206
#define SPECIES_GLIGAR                   207   // natDex 207
#define SPECIES_STEELIX                  208   // natDex 208
#define SPECIES_SNUBBULL                 209   // natDex 209
#define SPECIES_GRANBULL                 210   // natDex 210
#define SPECIES_GREAT_TUSK               211   // natDex 211
#define SPECIES_SCIZOR                   212   // natDex 212
#define SPECIES_SHUCKLE                  213   // natDex 213
#define SPECIES_HERACROSS                214   // natDex 214
#define SPECIES_SNEASEL                  215   // natDex 215
#define SPECIES_TEDDIURSA                216   // natDex 216
#define SPECIES_URSARING                 217   // natDex 217
#define SPECIES_SLUGMA                   218   // natDex 218
#define SPECIES_MAGCARGO                 219   // natDex 219
#define SPECIES_SWINUB                   220   // natDex 220
#define SPECIES_PILOSWINE                221   // natDex 221
#define SPECIES_RAGINGBOLT               222   // natDex 222
#define SPECIES_REMORAID                 223   // natDex 223
#define SPECIES_OCTILLERY                224   // natDex 224
#define SPECIES_GOUGINFIRE               225   // natDex 225
#define SPECIES_MANTINE                  226   // natDex 226
#define SPECIES_SKARMORY                 227   // natDex 227
#define SPECIES_HOUNDOUR                 228   // natDex 228
#define SPECIES_HOUNDOOM                 229   // natDex 229
#define SPECIES_KINGDRA                  230   // natDex 230
#define SPECIES_PHANPY                   231   // natDex 231
#define SPECIES_DONPHAN                  232   // natDex 232
#define SPECIES_PORYGON2                 233   // natDex 233
#define SPECIES_ROAR_MOON                234   // natDex 234
#define SPECIES_WALKINWAKE               235   // natDex 235
#define SPECIES_TYROGUE                  236   // natDex 236
#define SPECIES_HITMONTOP                237   // natDex 237
#define SPECIES_SMOOCHUM                 238   // natDex 238
#define SPECIES_ELEKID                   239   // natDex 239
#define SPECIES_MAGBY                    240   // natDex 240
#define SPECIES_MILTANK                  241   // natDex 241
#define SPECIES_BLISSEY                  242   // natDex 242
#define SPECIES_RAIKOU                   243   // natDex 243
#define SPECIES_ENTEI                    244   // natDex 244
#define SPECIES_SUICUNE                  245   // natDex 245
#define SPECIES_LARVITAR                 246   // natDex 246
#define SPECIES_PUPITAR                  247   // natDex 247
#define SPECIES_TYRANITAR                248   // natDex 248
#define SPECIES_PLUSLE                   249   // natDex 249
#define SPECIES_MINUN                    250   // natDex 250
#define SPECIES_CELEBI                   251   // natDex 251
#define SPECIES_ROSERADE                 252   // natDex 387
#define SPECIES_AMBIPOM                  253   // natDex 388
#define SPECIES_MISMAGIUS                254   // natDex 389
#define SPECIES_HONCHKROW                255   // natDex 390
#define SPECIES_WEAVILE                  256   // natDex 391
#define SPECIES_MAGNEZONE                257   // natDex 392
#define SPECIES_LICKILICKY               258   // natDex 393
#define SPECIES_RHYPERIOR                259   // natDex 394
#define SPECIES_TANGROWTH                260   // natDex 395
#define SPECIES_ELECTIVIRE               261   // natDex 396
#define SPECIES_MAGMORTAR                262   // natDex 397
#define SPECIES_TOGEKISS                 263   // natDex 398
#define SPECIES_YANMEGA                  264   // natDex 399
#define SPECIES_FROSLASS                 265   // natDex 400
#define SPECIES_GLISCOR                  266   // natDex 401
#define SPECIES_PORYGON_Z                267   // natDex 402
#define SPECIES_GALLADE                  268   // natDex 403
#define SPECIES_PROBOPASS                269   // natDex 404
#define SPECIES_DUSKNOIR                 270   // natDex 405
#define SPECIES_MAMOSWINE                271   // natDex 406
#define SPECIES_FARIGIRAF                272   // natDex 407
#define SPECIES_LEAFEON                  273   // natDex 408
#define SPECIES_GLACEON                  274   // natDex 409
#define SPECIES_ABYSS_EYE                275   // natDex 410
#define SPECIES_TENTACLE                 276   // natDex 411
#define SPECIES_TREECKO                  277   // natDex 252
#define SPECIES_GROVYLE                  278   // natDex 253
#define SPECIES_SCEPTILE                 279   // natDex 254
#define SPECIES_TORCHIC                  280   // natDex 255
#define SPECIES_COMBUSKEN                281   // natDex 256
#define SPECIES_BLAZIKEN                 282   // natDex 257
#define SPECIES_MUDKIP                   283   // natDex 258
#define SPECIES_MARSHTOMP                284   // natDex 259
#define SPECIES_SWAMPERT                 285   // natDex 260
#define SPECIES_POOCHYENA                286   // natDex 261
#define SPECIES_MIGHTYENA                287   // natDex 262
#define SPECIES_ZIGZAGOON                288   // natDex 263
#define SPECIES_LINOONE                  289   // natDex 264
#define SPECIES_WURMPLE                  290   // natDex 265
#define SPECIES_SILCOON                  291   // natDex 266
#define SPECIES_BEAUTIFLY                292   // natDex 267
#define SPECIES_CASCOON                  293   // natDex 268
#define SPECIES_DUSTOX                   294   // natDex 269
#define SPECIES_LOTAD                    295   // natDex 270
#define SPECIES_LOMBRE                   296   // natDex 271
#define SPECIES_LUDICOLO                 297   // natDex 272
#define SPECIES_SEEDOT                   298   // natDex 273
#define SPECIES_NUZLEAF                  299   // natDex 274
#define SPECIES_SHIFTRY                  300   // natDex 275
#define SPECIES_NINCADA                  301   // natDex 290
#define SPECIES_NINJASK                  302   // natDex 291
#define SPECIES_SHEDINJA                 303   // natDex 292
#define SPECIES_TAILLOW                  304   // natDex 276
#define SPECIES_SWELLOW                  305   // natDex 277
#define SPECIES_SHROOMISH                306   // natDex 285
#define SPECIES_BRELOOM                  307   // natDex 286
#define SPECIES_REGIGIGAS                308   // natDex 327
#define SPECIES_WINGULL                  309   // natDex 278
#define SPECIES_PELIPPER                 310   // natDex 279
#define SPECIES_SURSKIT                  311   // natDex 283
#define SPECIES_MASQUERAIN               312   // natDex 284
#define SPECIES_WAILMER                  313   // natDex 320
#define SPECIES_WAILORD                  314   // natDex 321
#define SPECIES_SKITTY                   315   // natDex 300
#define SPECIES_DELCATTY                 316   // natDex 301
#define SPECIES_KECLEON_317              317   // natDex 352
#define SPECIES_BALTOY                   318   // natDex 343
#define SPECIES_CLAYDOL                  319   // natDex 344
#define SPECIES_NOSEPASS                 320   // natDex 299
#define SPECIES_TORKOAL                  321   // natDex 324
#define SPECIES_SABLEYE                  322   // natDex 302
#define SPECIES_BARBOACH                 323   // natDex 339
#define SPECIES_WHISCASH                 324   // natDex 340
#define SPECIES_CORSOLA                  325   // natDex 370
#define SPECIES_CORPHISH                 326   // natDex 341
#define SPECIES_CRAWDAUNT                327   // natDex 342
#define SPECIES_FEEBAS                   328   // natDex 349
#define SPECIES_MILOTIC                  329   // natDex 350
#define SPECIES_CARVANHA                 330   // natDex 318
#define SPECIES_SHARPEDO                 331   // natDex 319
#define SPECIES_TRAPINCH                 332   // natDex 328
#define SPECIES_VIBRAVA                  333   // natDex 329
#define SPECIES_FLYGON                   334   // natDex 330
#define SPECIES_MAKUHITA                 335   // natDex 296
#define SPECIES_HARIYAMA                 336   // natDex 297
#define SPECIES_ELECTRIKE                337   // natDex 309
#define SPECIES_MANECTRIC                338   // natDex 310
#define SPECIES_NUMEL                    339   // natDex 322
#define SPECIES_CAMERUPT                 340   // natDex 323
#define SPECIES_SPHEAL                   341   // natDex 363
#define SPECIES_SEALEO                   342   // natDex 364
#define SPECIES_WALREIN                  343   // natDex 365
#define SPECIES_CACNEA                   344   // natDex 331
#define SPECIES_CACTURNE                 345   // natDex 332
#define SPECIES_SNORUNT                  346   // natDex 361
#define SPECIES_GLALIE                   347   // natDex 362
#define SPECIES_LUNATONE                 348   // natDex 337
#define SPECIES_SOLROCK                  349   // natDex 338
#define SPECIES_YGGDREON                 350   // natDex 298
#define SPECIES_SPOINK                   351   // natDex 325
#define SPECIES_GRUMPIG                  352   // natDex 326
#define SPECIES_PLUSLE_353               353   // natDex 311
#define SPECIES_MINUN_354                354   // natDex 312
#define SPECIES_MAWILE_355               355   // natDex 303
#define SPECIES_MEDITITE                 356   // natDex 307
#define SPECIES_MEDICHAM                 357   // natDex 308
#define SPECIES_SWABLU                   358   // natDex 333
#define SPECIES_ALTARIA                  359   // natDex 334
#define SPECIES_BLAZIKEN_360             360   // natDex 360
#define SPECIES_DUSKULL                  361   // natDex 355
#define SPECIES_DUSCLOPS                 362   // natDex 356
#define SPECIES_ROSELIA                  363   // natDex 315
#define SPECIES_SLAKOTH                  364   // natDex 287
#define SPECIES_VIGOROTH                 365   // natDex 288
#define SPECIES_SLAKING                  366   // natDex 289
#define SPECIES_GULPIN                   367   // natDex 316
#define SPECIES_SWALOT                   368   // natDex 317
#define SPECIES_TROPIUS                  369   // natDex 357
#define SPECIES_WHISMUR                  370   // natDex 293
#define SPECIES_LOUDRED                  371   // natDex 294
#define SPECIES_EXPLOUD                  372   // natDex 295
#define SPECIES_ANNIHILAPE               373   // natDex 366
#define SPECIES_DUDUNSPARS               374   // natDex 367
#define SPECIES_URSALUNA                 375   // natDex 368
#define SPECIES_ABSOL                    376   // natDex 359
#define SPECIES_SHUPPET                  377   // natDex 353
#define SPECIES_BANETTE                  378   // natDex 354
#define SPECIES_SEVIPER                  379   // natDex 336
#define SPECIES_ZANGOOSE                 380   // natDex 335
#define SPECIES_RELICANTH                381   // natDex 369
#define SPECIES_ARON                     382   // natDex 304
#define SPECIES_LAIRON                   383   // natDex 305
#define SPECIES_AGGRON                   384   // natDex 306
#define SPECIES_CASTFORM                 385   // natDex 351
#define SPECIES_VOLBEAT                  386   // natDex 313
#define SPECIES_ILLUMISE                 387   // natDex 314
#define SPECIES_LILEEP                   388   // natDex 345
#define SPECIES_CRADILY                  389   // natDex 346
#define SPECIES_ANORITH                  390   // natDex 347
#define SPECIES_ARMALDO                  391   // natDex 348
#define SPECIES_RALTS                    392   // natDex 280
#define SPECIES_KIRLIA                   393   // natDex 281
#define SPECIES_GARDEVOIR                394   // natDex 282
#define SPECIES_BAGON                    395   // natDex 371
#define SPECIES_SHELGON                  396   // natDex 372
#define SPECIES_SALAMENCE                397   // natDex 373
#define SPECIES_BELDUM                   398   // natDex 374
#define SPECIES_METANG                   399   // natDex 375
#define SPECIES_METAGROSS                400   // natDex 376
#define SPECIES_REGIROCK                 401   // natDex 377
#define SPECIES_REGICE                   402   // natDex 378
#define SPECIES_REGISTEEL                403   // natDex 379
#define SPECIES_TLACHTGA                 404   // natDex 382
#define SPECIES_DINOGATOR                405   // natDex 383
#define SPECIES_AV_DRAGON                406   // natDex 384
#define SPECIES_DEEPMAIDEN               407   // natDex 380
#define SPECIES_NARMER                   408   // natDex 381
#define SPECIES_JIRACHI                  409   // natDex 385
#define SPECIES_REEFSOLA                 410   // natDex 386
#define SPECIES_CHIMECHO                 411   // natDex 358

#endif
